# Generated by Django 3.2 on 2021-05-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(default=0, max_length=50)),
                ('p_content', models.TextField()),
                ('pos_votes', models.IntegerField()),
                ('neg_votes', models.IntegerField()),
                ('p_score', models.IntegerField()),
                ('p_dateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
