# Generated by Django 3.2 on 2021-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_postimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimagemodel',
            name='img_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
