# Generated by Django 3.2 on 2021-05-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_postimagemodel_img_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimagemodel',
            name='p_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Posts.postmodel', verbose_name='PostModel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='p_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
