# Generated by Django 3.2 on 2021-05-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0011_auto_20210515_0008'),
        ('Posts', '0005_postmodel_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='u_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tags.tagmodel', verbose_name='Tagmodel'),
        ),
    ]
