# Generated by Django 3.2 on 2021-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20210515_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='neg_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='p_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pos_votes',
            field=models.IntegerField(default=0),
        ),
    ]
