# Generated by Django 3.2 on 2021-05-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20210516_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimagemodel',
            name='p_image',
        ),
        migrations.AddField(
            model_name='postimagemodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Posts.postmodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='p_coverimage',
            field=models.ImageField(null=True, upload_to='coverimage'),
        ),
    ]
