# Generated by Django 3.2 on 2021-05-29 08:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210513_0601'),
        ('Posts', '0008_auto_20210518_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='voted',
            field=models.ManyToManyField(blank=True, default=None, related_name='voted', to='User.UserModel'),
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Posts.postmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='User.usermodel')),
            ],
        ),
    ]
