# Generated by Django 3.2 on 2021-05-29 12:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210513_0601'),
        ('Posts', '0009_auto_20210529_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PositiveVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='neg_votes',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pos_votes',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='voted',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='nvoted',
            field=models.ManyToManyField(blank=True, default=None, related_name='nvoted', to='User.UserModel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='pvoted',
            field=models.ManyToManyField(blank=True, default=None, related_name='pvoted', to='User.UserModel'),
        ),
        migrations.DeleteModel(
            name='PostVote',
        ),
        migrations.AddField(
            model_name='positivevote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Posts.postmodel'),
        ),
        migrations.AddField(
            model_name='positivevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='User.usermodel'),
        ),
        migrations.AddField(
            model_name='negativevote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Posts.postmodel'),
        ),
        migrations.AddField(
            model_name='negativevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='User.usermodel'),
        ),
    ]
