# Generated by Django 3.2 on 2021-06-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='p_score',
        ),
    ]
