# Generated by Django 3.2 on 2021-06-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_remove_postmodel_p_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='p_com',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
