# Generated by Django 3.2 on 2021-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_postmodel_p_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='p_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
