# Generated by Django 3.2 on 2021-05-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=20)),
                ('a_pass', models.CharField(max_length=20, null=True)),
                ('a_username', models.CharField(max_length=20, null=True)),
                ('a_loctype', models.CharField(max_length=20, null=True)),
                ('a_location', models.CharField(max_length=50, null=True)),
                ('a_age', models.IntegerField()),
            ],
        ),
    ]
