# Generated by Django 3.2 on 2021-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default=0, max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
