# Generated by Django 3.2 on 2021-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0002_auto_20210502_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='t_country',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='t_place',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='t_state',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='tag_disc',
            field=models.TextField(default=0),
        ),
    ]
