# Generated by Django 3.2 on 2021-05-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0004_tagmodel_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_title',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
