# Generated by Django 3.2 on 2021-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0005_auto_20210503_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
