# Generated by Django 3.2 on 2021-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0006_alter_tagmodel_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_image',
            field=models.ImageField(upload_to='tags'),
        ),
    ]
