# Generated by Django 3.2 on 2021-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0007_alter_tagmodel_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='t_country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='t_place',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='t_state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
