# Generated by Django 3.2 on 2021-05-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0010_auto_20210515_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='t_country',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='t_place',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='t_state',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
