# Generated by Django 3.2 on 2021-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0011_auto_20210515_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_title', models.CharField(default=0, max_length=40)),
                ('tr_contrnt', models.TextField(default=0)),
            ],
        ),
    ]
