# Generated by Django 3.2 on 2021-05-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0012_tagrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagrequest',
            old_name='tr_contrnt',
            new_name='tr_content',
        ),
        migrations.AddField(
            model_name='tagrequest',
            name='tr_loc',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
