# Generated by Django 3.2 on 2021-05-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210513_0601'),
        ('Tags', '0015_tagrequest_tr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagrequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.usermodel', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tagrequest',
            name='tr_type',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
