# Generated by Django 3.2 on 2021-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0019_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
    ]
