# Generated by Django 3.2 on 2021-05-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default=0, max_length=20)),
                ('u_age', models.IntegerField()),
                ('u_pic', models.ImageField(upload_to='')),
                ('u_country', models.CharField(default=0, max_length=20)),
                ('u_state', models.CharField(default=0, max_length=20)),
                ('u_place', models.CharField(default=0, max_length=20)),
                ('u_security', models.BooleanField()),
            ],
        ),
    ]
