# Generated by Django 3.2 on 2021-05-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_security',
            field=models.BooleanField(default=0),
        ),
    ]
