# Generated by Django 3.2 on 2021-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_usermodel_u_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_pic',
            field=models.ImageField(upload_to='user_dp'),
        ),
    ]
