# Generated by Django 3.2 on 2021-05-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_usermodel_u_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_pass',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='u_username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='u_name',
            field=models.CharField(max_length=20),
        ),
    ]
