# Generated by Django 3.2 on 2021-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20210611_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_verified',
            field=models.BooleanField(default=0),
        ),
    ]
