# Generated by Django 3.2 on 2021-06-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_usermodel_u_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_pass',
            field=models.CharField(max_length=20),
        ),
    ]
