# Generated by Django 3.2 on 2021-06-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20210628_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='following',
        ),
    ]
