# Generated by Django 4.2.25 on 2025-10-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_delete_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempProof',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='u_pic',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='u_place',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='u_latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='u_longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
