# Generated by Django 4.2.25 on 2025-10-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_delete_tempproof_remove_usermodel_u_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_nearby_cities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
