# Generated by Django 4.2.25 on 2025-10-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_usermodel_u_nearby_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='u_nearby_cities',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='u_selected_nearby_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
