# Generated by Django 4.2.25 on 2025-10-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_remove_usermodel_u_nearby_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_detected_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
