# Generated by Django 4.2.25 on 2025-10-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_usermodel_u_detected_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
